# router auth
@base = http://localhost:3000
# 使用注册或登入后会自动设置 cookie token

###
@name = 用户登录 mofu
POST {{base}}/auth/login
content-type: application/json

{
	"email": "mofu@gmail.com",
	"passwd": "mofumofu"
}

###
@name = 用户登录 test
POST {{base}}/auth/login
content-type: application/json

{
	"email": "test@gmail.com",
	"passwd": "12345678"
}

###
@name = 用户注册
POST {{base}}/auth/register
Content-Type: application/json

{
	"email": "mofu@gmail.com",
	"passwd": "mofumofu",
	"nick": "mofu"
}

###
GET {{base}}/env

###
GET {{base}}/audit?page=1

###
GET {{base}}/audit/count

###
POST {{base}}/inject
Content-Type: application/json

{
	"user": "10473831864042"
}
