# router auth
@base = http://localhost:3000/api/v1
# 使用注册或登入后会自动设置 cookie token

###
@name = 用户登录 mofu
POST {{base}}/auth/login
content-type: application/json

{
	"email": "mofu@gmail.com",
	"passwd": "mofumofu"
}

###
@name = 用户登录 test
POST {{base}}/auth/login
content-type: application/json

{
	"email": "test@gmail.com",
	"passwd": "mofumofu"
}

###
@name = 用户注册
POST {{base}}/auth/register
Content-Type: application/json

{
	"email": "mofu@gmail.com",
	"passwd": "mofumofu",
	"nick": "mofu"
}

###