# router group
@base = http://localhost:3000/api/v1
@group = 10474362077060

###
@name = 创建群组
POST {{base}}/group
Content-Type: application/json

{
  "name": "My Group 2"
}

###
@name = 群组详情
GET {{base}}/group/{{group}}/detail

###
@name = 列出我的群组
GET {{base}}/group/@me

###