# router relation
@base = http://localhost:3000
@user = 10290909060497
@relation = 34749064807952

###
@name = 创建关系
POST {{base}}/relation/create/{{user}}
###

###
@name = 详情
GET {{base}}/relation/{{relation}}/detail

###
@name = 列出所有我的关系
GET {{base}}/relation/@my
###

###
@name = 发送私聊消息
POST {{base}}/relation/{{relation}}/message
Content-Type: application/json

{
  "content": "test"
}